server:
  port: 8087
spring:
  data:
    mongodb:
      port: 27017
      host: 127.0.0.1
      database: bankingmanagement
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,threaddump,env,caches
  endpoint:
    health:
      show-details: always